### PR TITLE
Nvidia 346.59 test bump, 

### PR DESCRIPTION
**Pull request by necrose99**
nvidia-drivers-346.59.ebuild
nvidia-userspace-346.59.ebuild
Version 	346.59
Release Date 	Tue Apr 07, 2015
http://us.download.nvidia.com/XFree86/Linux-x86_64/346.59/NVIDIA-Linux-x86_64-346.59.run
willing to be the victim if you slot it  to limbo , 
sometimes the updates from gentoo/sabayon go smooth other times I'm using the run to build my kernel modules , then letting sab packages "fix" any settings , mobile gpu's seem to be the most adversely affected, since i know how to fix or work around, can recover if it borks. (I've had to become rather adept at this lol) nvidia-kernel-module ? still cooking /usr/src/nvidia{$pv}  I'd just re-bake if it broke 
Knowing it likely will  blow up on my mobile chipset.....  i can send anything (logs/etc)  back necessary to fix

### CODE REVIEW

**Comment by lxnay** [comment]
You forgot media-video/nvidia-settings

**Comment by necrose99** [comment]
done deal made a bump as well, I pray this time i'm not having to debug, but good to go if i have too.

**Comment by lxnay** [comment]
Now I see more commits than before, unrelated to nvidia stuff. Is this expected?

**Comment by necrose99** [comment]
<joost_op> mudler: if bored -> net-print/brother-hl5340d-drivers and net-print/xerox-phaser6000-drivers still dep on app-emulation/emul-linux-x86-baselibs 
meh i figgured I'd take a poke at it if not up to spec i'll drop it.

**Comment by necrose99** [comment]
rebsed with a diff

**Pull request closed without merging**
