### PR TITLE
[app-misc/sabayon-version] switch to Python 3 (once)

### PR DESCRIPTION
**Pull request by Enlik**
This commit changes only the skel file.

### CODE REVIEW

**Comment by Enlik** [comment]
@mudler @geaaru @joostruis @optiz0r It's about time.
Entropy will not break as it forces 2.7.

**Comment by mudler** [comment]
https://github.com/Sabayon/docker-stage3-amd64/commit/41fbd981ac65a06e88a79cb1e5dda62273b746ca

**Comment by Enlik** [comment]
How did it turn out so far?

**Comment by mudler** [comment]
3.6 on ISOs looks good, also we (finally) dropped https://github.com/Sabayon/docker-stage3-base-amd64 in favor of using stage3 directly from Gentoo :tada:  :tada:

**Comment by Enlik** [comment]
OK, let's keep in mind it'll be used on the next version or revision bump (if this file will be the base).

**Pull request merged**
