### PR TITLE
Bump Gcc 5.4.0-r3 stuff

### PR DESCRIPTION
**Pull request by geaaru**

### CODE REVIEW

**Comment by mudler** [comment]
LGTM, somebody else tested it?

**Comment by geaaru** [comment]
Hi, I tested compilation on both arm (bpi) and amd64 compilation (only of sys-devel/gcc and sys-devel/base-gcc) on a fresh sabayon images. It seems that there aren't errors on compilation. 
But it is required that a lot of packages must be rebuild.
My cent.

**Comment by mudler** [comment]
Indeed i'm refeering to others. I assume you tested it already :) Did you just compiled it or rebuilt also other packages with it?  btw, that package is stable now, so you can stabilize it

**Comment by mudler** [comment]
Notes for future: we should fork toolchain eclass and handle all of this from the eclasses instead ebuilds, that would make life easier for bumping it in the future.

**Comment by geaaru** [comment]
On arm (bpi) I recompiled all packages.

Is there only one thing to check. On previous ebuild set of gcc profile was done on base-gcc package, but so after sys-devel/base-gcc emerge doesn't work correctly until is avaiable sys-devel/gcc. Is there a reason because set of profile was present on base-gcc ebuild and not gcc ?

**Comment by geaaru** [comment]
I investigate about set of profile... maybe is needed because else link to libraries are not correctly set.
```
ls -l /usr/lib/libstdc++.so.6 
lrwxrwxrwx 1 root root 64 Mar  8 18:59 /usr/lib/libstdc++.so.6 -> /usr/lib/gcc/armv7a-hardfloat-linux-gnueabi/4.9.3/libstdc++.so.6
```
But probably is correct set new profile on merge package but then on post_inst reset previous gcc version.

**Comment by mudler** [comment]
Thanks for working on this. Now gcc/base-gcc split is handled by sabayon-toolchain eclass

**Pull request closed without merging**
